Dir["#{File.dirname(__FILE__)}/spec/tasks/**/*.rake"].sort.each { |ext| load ext }

flexspec_config.repo_location = '..'

test_config.app_name = 'Flexspec'
test_config.test_dir = "src"
test_config.test_suite_dir = 'src'